### ISSUE TITLE
add bot checks to every command

### ISSUE THREAD

**Issue by MCOfficer** [MCOfficer/EndlessSky-Discord-Bot#103]
cause bot interaction is a sin.

**Comment by warp-core** [comment]
Is this not just add some if statements?
Or just modify canDoCommand to return false for bots.
Isn't that called for all commands?

**Comment by MCOfficer** [comment]
canDoCommand is only used for the PlayerControl, since it also contains voice channel checks.
nevertheless, it's a simple oneliner (one for every command).

**Comment by warp-core** [comment]
~Just make sure you don't change the operators when you change other things~

**Comment by MCOfficer** [comment]
silence! @warp-core
