### ISSUE TITLE
-show(data) does not work properly with shipyards and outfitters

### ISSUE THREAD

**Issue by Bladewood** [MCOfficer/EndlessSky-Discord-Bot#116]
The `-show` and `-showdata` commands fail with `shipyard`s and `outfitter`s unless the argument is properly capitalized and given quotation marks.

For example, `-show Basic Ships` fails, as do `-showdata "lovelace basics"` and `-showdata outfitter Common Outfits`. But `-showdata shipyard "Tarazed Advanced"` works.

**Comment by tehhowch** [comment]
For these and some other category keywords you have to write the literal matchable string. Changing this is probably ok, now that we have category restriction.
