### ISSUE TITLE
"DJ" role necessary?

### ISSUE THREAD

**Issue by MCOfficer** [MCOfficer/EndlessSky-Discord-Bot#29]
-volume seems not to work for common users.

need someone to confirm this, maybe i'm just too dumb.

example:
me: -volume 50
james: `Audio-Player: Current player volume: 100`

**Comment by MCOfficer** [comment]
volume can only be changed by DJs, considering to keep the DJ role or overhaul that system

**Comment by tehhowch** [comment]
maybe attempts to set volume by non-DJ starts a vote poll for the new volume. So a group of non-DJs can lower the volume, but the DJ can always set the new volume

**Comment by MCOfficer** [comment]
will be reworked eventually. #48
