### ISSUE TITLE
Sort -help command

### ISSUE THREAD

**Issue by MCOfficer** [MCOfficer/EndlessSky-Discord-Bot#30]
^

**Comment by tehhowch** [comment]
It may be better to have multiple sort groups, e.g. first group by associated task, then sort alphabetically. James can then introduce each task, e.g. ***Lookup Commands***, ***Music Commands***, etc

**Comment by MCOfficer** [comment]
done with #d6825c1d591898f4949df1f2e1e9e803cf52d87e
