### ISSUE TITLE
rework dj restriction system

### ISSUE THREAD

**Issue by MCOfficer** [MCOfficer/EndlessSky-Discord-Bot#48]
i gotta think about how to do this, but it's on my list.

1. allow any shuffles etc. when the user is the only one listening
2. (maybe) decide via vote for multiple users

the way it currently is, stuff like -shuffle is restricted to pretty much everyone.

**Comment by 1010todd** [comment]
I think voting is the best or maybe some kind of master? like someone who can do anything without voting, but just an idea.

**Comment by MCOfficer** [comment]
we already got DJs who can do anything. so yeah, it's probably better to have both: direct commands for DJs, voting for peasants :p

**Comment by MCOfficer** [comment]
so, here's the roadmap:

- the dj role stays the same, with full privileges (no voting)
- if a vote is running and a DJ votes, the vote is instantly successful
- **shuffle, volume, pause, resume and skip get a votesystem** (additionally to the direct command by DJs)
- voteskip gets removed in favor of -skip

**Comment by MCOfficer** [comment]
most of this is done with ebdc4ebd8b0ddf1a88739b26b37d14063f804261 .
i will leave -volume the way it is, because

- a volume other than 10 leads to a higher server load
- one can simply change james' volume locally without affecting other users
- it is a pain in the ass to coordinate multiple users voting for multiple volume values, while only yes/no votes are supported
