### ISSUE TITLE
let users define what type of data they want to lookup

### ISSUE THREAD

**Issue by MCOfficer** [MCOfficer/EndlessSky-Discord-Bot#64]
i feeel like the lookup System Needs an overhaul, mainly because of the amount of conflicts we Keep running into (e.g. planet & ship `albatross`).
my proposal would be to let users specify what they search for as Parameter:
`-lookup planet albatross`

**Comment by tehhowch** [comment]
It already does this, to an extent - the person needs to specify the correct capitalization and quotation as otherwise the capitalization and encapsulation functions will cause a non-match.
`planet Albatross` and `ship "Albatross"` both work and return the correct data

**Comment by tehhowch** [comment]
To remedy, we would want to check the argument length, and if a category token is given, check that it is a supported category (or just a part of the search term).
If it is a supported category, then we pop it and test the remainder as normal (e.g. varied encapsulation and capitalization, ship variant lookup) with the specifier as a prefix

**Comment by MCOfficer** [comment]
#65
