### ISSUE TITLE
old okhttp version?

### ISSUE THREAD

**Issue by tehhowch** [MCOfficer/EndlessSky-Discord-Bot#67]
0e72af56573af577aaa33b0f29f0bf4a9cb15bb7
Should this be
```
compile 'com.squareup.okhttp3:okhttp:3.9.0
```
or some other current equivalent?
![image](https://user-images.githubusercontent.com/20871346/31129120-480d38f4-a819-11e7-85b3-12b8b6742362.png)

**Comment by MCOfficer** [comment]
573e5d2206c36d7a35675dda0727b17d799e0256, thanks for noticing
