### ISSUE TITLE
skip wildcards for requesters?

### ISSUE THREAD

**Issue by MCOfficer** [MCOfficer/EndlessSky-Discord-Bot#77]
e.g. when i add a song, should i be able to skip that song without a vote?
not sure how complicated the implementation would be.

**Comment by tehhowch** [comment]
As i mentioned on discord, you could do this a few ways.
Simplest is to just make another linked list that parallels the queue, and add/remove to it whenever you add/remove to the queue.

No matter the implementation to store the requested name, your vote handlers get a smidge harder - they check the vote count and the privilege of the voter. (Could be done in the caller too, just have to clear vote on success, in case the owner isn't the first voter)
Implementing a requested by list would also make it possible to `-unplay` and remove an entry from a bad search

**Comment by MCOfficer** [comment]
1cdae0bf891ae110a4a62d58b86b5e680b9cbb4f
